INDICATOR_SP_PER_COUNTRY = {
    'FI': [  # Finland
        'Anthus trivialis', 'Cuculus canorus', 'Dryocopus martius',
        'Garrulus glandarius', 'Lanius collurio', 'Muscicapa striata',
        'Phoenicurus phoenicurus', 'Phylloscopus collybita',
        'Phylloscopus trochilus', 'Prunella modularis',
        'Regulus regulus', 'Sylvia borin', 'Sylvia curruca',
        'Tringa ochropus', 'Turdus viscivorus',
    ],

    'NO': [  # Norway
        'Anthus trivialis', 'Columba palumbus', 'Dendrocopos major',
        'Muscicapa striata', 'Periparus ater', 'Phoenicurus phoenicurus',
        'Phylloscopus collybita', 'Phylloscopus trochilus',
        'Prunella modularis', 'Regulus regulus',
        'Tringa nebularia', 'Turdus philomelos',
    ],

    'SE': [  # Sweden
        'Aegithalos caudatus', 'Anthus trivialis', 'Bombycilla garrulus',
        'Cuculus canorus', 'Dendrocopos major', 'Garrulus glandarius',
        'Muscicapa striata', 'Periparus ater', 'Phoenicurus phoenicurus',
        'Phylloscopus collybita', 'Phylloscopus trochilus',
        'Prunella modularis', 'Regulus regulus', 'Sylvia curruca',
        'Tetrao tetrix', 'Tringa ochropus', 'Turdus viscivorus',
    ],

    'FR': [  # France
        'Anthus trivialis', 'Coccothraustes coccothraustes',
        'Cuculus canorus', 'Dendrocopos medius', 'Dendrocopos minor',
        'Garrulus glandarius', 'Jynx torquilla', 'Periparus ater',
        'Phoenicurus phoenicurus', 'Phylloscopus bonelli',
        'Phylloscopus sibilatrix', 'Phylloscopus trochilus',
        'Regulus ignicapillus', 'Regulus regulus',
        'Sitta europaea', 'Sylvia borin', 'Sylvia cantillans',
    ],

    'ES': [  # Spain
        'Accipiter nisus', 'Aegithalos caudatus', 'Anthus trivialis',
        'Certhia brachydactyla', 'Coccothraustes coccothraustes',
        'Cyanistes caeruleus', 'Garrulus glandarius', 'Periparus ater',
        'Phylloscopus bonelli', 'Regulus ignicapillus',
        'Regulus regulus', 'Sitta europaea',
        'Sylvia borin', 'Sylvia hortensis',
    ],

    'AT': [  # Austria
        'Aegithalos caudatus', 'Certhia familiaris',
        'Coccothraustes coccothraustes', 'Dryocopus martius',
        'Garrulus glandarius', 'Periparus ater',
        'Phylloscopus collybita', 'Phylloscopus trochilus',
        'Regulus ignicapillus', 'Regulus regulus',
        'Sylvia atricapilla', 'Troglodytes troglodytes',
    ],

    'BE': [  # Belgium
        'Aegithalos caudatus', 'Buteo buteo',
        'Coccothraustes coccothraustes', 'Cuculus canorus',
        'Dendrocopos major', 'Garrulus glandarius',
        'Periparus ater', 'Phylloscopus collybita',
        'Phylloscopus trochilus', 'Poecile palustris',
        'Regulus ignicapillus', 'Regulus regulus',
        'Sitta europaea', 'Sylvia borin',
        'Turdus viscivorus',
    ],

    'DK': [  # Denmark
        'Anthus trivialis', 'Buteo buteo', 'Certhia familiaris',
        'Dendrocopos major', 'Garrulus glandarius',
        'Muscicapa striata', 'Periparus ater',
        'Phoenicurus phoenicurus', 'Phylloscopus sibilatrix',
        'Phylloscopus trochilus', 'Regulus regulus',
        'Sitta europaea', 'Sylvia atricapilla',
        'Sylvia borin', 'Turdus viscivorus',
    ],

    'IE': [  # Ireland
        'Corvus corax', 'Cuculus canorus',
        'Erithacus rubecula', 'Fringilla coelebs',
        'Periparus ater', 'Phylloscopus trochilus',
        'Regulus regulus', 'Sylvia atricapilla',
        'Turdus philomelos', 'Turdus viscivorus',
    ],

    'NL': [  # Netherlands
        'Accipiter nisus', 'Aegithalos caudatus',
        'Anthus trivialis', 'Buteo buteo',
        'Certhia brachydactyla',
        'Coccothraustes coccothraustes',
        'Dendrocopos major', 'Dendrocopos minor',
        'Garrulus glandarius', 'Lullula arborea',
        'Luscinia megarhynchos', 'Oriolus oriolus',
        'Periparus ater', 'Phoenicurus phoenicurus',
        'Phylloscopus sibilatrix', 'Picus viridis',
        'Regulus regulus', 'Streptopelia turtur',
        'Sylvia borin',
    ],

    'CH': [  # Switzerland
        'Aegithalos caudatus', 'Anthus trivialis',
        'Buteo buteo', 'Cuculus canorus',
        'Emberiza citrinella', 'Garrulus glandarius',
        'Lanius collurio', 'Nucifraga caryocatactes',
        'Passer montanus', 'Phoenicurus phoenicurus',
        'Phylloscopus sibilatrix', 'Picus viridis',
        'Regulus ignicapillus', 'Regulus regulus',
        'Serinus citrinella', 'Sitta europaea',
        'Sylvia atricapilla', 'Sylvia borin',
        'Turdus torquatus',
    ],

    'UK': [  # United Kingdom
        'Anthus trivialis', 'Buteo buteo',
        'Carduelis flammea', 'Carduelis spinus',
        'Cuculus canorus', 'Garrulus glandarius',
        'Periparus ater', 'Phoenicurus phoenicurus',
        'Phylloscopus sibilatrix', 'Phylloscopus trochilus',
        'Picus viridis', 'Poecile palustris',
        'Regulus regulus', 'Sitta europaea',
        'Streptopelia turtur', 'Sylvia borin',
    ],

    'CZ': [  # Czechia
        'Columba palumbus', 'Corvus corax',
        'Dryocopus martius', 'Erithacus rubecula',
        'Ficedula albicollis', 'Periparus ater',
        'Phylloscopus sibilatrix', 'Prunella modularis',
        'Pyrrhula pyrrhula', 'Regulus ignicapillus',
        'Regulus regulus', 'Sylvia atricapilla',
        'Sylvia borin', 'Turdus viscivorus',
    ],

    'EE': [  # Estonia
        'Columba palumbus', 'Cuculus canorus',
        'Erithacus rubecula', 'Phylloscopus sibilatrix',
        'Phylloscopus trochilus', 'Sylvia atricapilla',
        'Sylvia borin', 'Turdus merula',
        'Turdus philomelos',
    ],

    'DE': [  # Germany
        'Accipiter nisus', 'Anthus trivialis',
        'Buteo buteo', 'Certhia familiaris',
        'Coccothraustes coccothraustes',
        'Dendrocopos major', 'Dendrocopos medius',
        'Dendrocopos minor', 'Garrulus glandarius',
        'Oriolus oriolus', 'Periparus ater',
        'Phylloscopus sibilatrix', 'Phylloscopus trochilus',
        'Picus canus', 'Regulus ignicapillus',
        'Regulus regulus', 'Streptopelia turtur',
        'Turdus viscivorus',
    ],

    'PL': [  # Poland
        'Accipiter nisus', 'Aegithalos caudatus',
        'Anthus trivialis', 'Coccothraustes coccothraustes',
        'Dendrocopos major', 'Erithacus rubecula',
        'Garrulus glandarius', 'Oriolus oriolus',
        'Periparus ater', 'Phoenicurus phoenicurus',
        'Phylloscopus sibilatrix', 'Phylloscopus trochilus',
        'Prunella modularis', 'Regulus ignicapillus',
        'Regulus regulus', 'Streptopelia turtur',
        'Sylvia atricapilla', 'Sylvia borin',
        'Tringa ochropus', 'Troglodytes troglodytes',
        'Turdus viscivorus',
    ],

    'BG': [  # Bulgaria
        'Cuculus canorus', 'Fringilla coelebs',
        'Garrulus glandarius', 'Parus major',
    ],

    'RO': [  # Romania
        'Cuculus canorus', 'Dendrocopos major',
        'Garrulus glandarius', 'Oriolus oriolus',
        'Phylloscopus collybita', 'Sturnus vulgaris',
        'Sylvia atricapilla',
    ],
    'DEFAULT': [  # Europe (All)
        'Accipiter nisus',
        'Anthus trivialis',
        'Buteo buteo',
        'Carduelis spinus',
        'Coccothraustes coccothraustes',
        'Cuculus canorus',
        'Dendrocopos medius',
        'Dendrocopos minor',
        'Garrulus glandarius',
        'Muscicapa striata',
        'Oriolus oriolus',
        'Periparus ater',
        'Phoenicurus phoenicurus',
        'Phylloscopus sibilatrix',
        'Phylloscopus trochilus',
        'Picus canus',
        'Picus viridis',
        'Regulus ignicapillus',
        'Regulus regulus',
        'Serinus citrinella',
        'Sitta europaea',
        'Streptopelia turtur',
        'Sylvia borin',
        'Sylvia cantillans',
        'Tringa nebularia',
        'Tringa ochropus',
    ]
}
